# Site settings
title: Ricochet Refresh
email:
description: A Blueprint For Free speech initiative to update and improve Ricochet

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://www.ricochetrefresh.net" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/r2refresh
  # - title: facebook
  #  url: 
  # - title: google-plus
  #  url: 
  #- title: github
  #  url: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
  - less
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]
# Build settings
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
